server.port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:employeedb
    username: admin
    password: adminpwd

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        connection:
          autocommit: false
    hibernate:
      ddl-auto: none

  # In-Memory cache
  cache:
    type: caffeine
    cache-names: roleCacheManager
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats

  h2.console.enabled: true

  mvc.favicon.enabled: false

logging.level.root: info