basicauth:
  config:
    - username: employee_app
      role: APP_ADMIN
      password: password

spring:
  datasource:
    platform: integration-test
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_database
    username: testuser
    password: testuserpwd

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        connection:
          autocommit: false
    hibernate:
      ddl-auto: none

  # In-Memory cache
  cache:
    type: caffeine
    cache-names: roleCacheManager
    caffeine:
      spec: maximumSize=100,expireAfterWrite=600s

logging.level.root: info