DROP TABLE ROLE IF EXISTS;
DROP TABLE EMPLOYEE IF EXISTS;
DROP TABLE PROJECT IF EXISTS;

CREATE TABLE ROLE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE EMPLOYEE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE PROJECT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

CREATE INDEX idx_firstname ON EMPLOYEE(FIRSTNAME);
CREATE INDEX idx_surname ON EMPLOYEE(SURNAME);
CREATE INDEX idx_roleid_fk ON EMPLOYEE(ROLE_ID);
CREATE INDEX idx_project_name ON PROJECT(NAME);
CREATE INDEX idx_employeeid_fk ON PROJECT(EMPLOYEE_ID);
