DROP TABLE ROLE IF EXISTS;
DROP TABLE EMPLOYEE IF EXISTS;
DROP TABLE PROJECT IF EXISTS;

CREATE TABLE ROLE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE EMPLOYEE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE PROJECT(
    ID VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT PK_PROJECT_EMPLOYEE PRIMARY KEY (ID, NAME, EMPLOYEE_ID)
);

--TODO: Have create procedure and index based on the requirement need